theme: jekyll-theme-cayman
title: Gemstone.PQDS
description: GPA Gemstone PQDS Library
github:
  repository_name: gemstone/pqds
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
